import json, re, time, random

CSV_DATA = """Name,Composer,Voicing,# Of Copies,Last Year Performed,Description (optional)
21 Guns,Roger Emerson,SSA,3,,
A Blessing,Jerry Porterfield,3-Part Mixed,1,,
A Christmas Wish,Ed Harris,SAB,5,,
A Festive Fa La La`,Patrick M. Liebergen,SAB,1,,
A Galic Blessing,John Rutter,SATB,1,,
A Gift For Every Child,Sally K. Albricht,3-Part Mixed,19,,
A Holly Jolly Christmas,Mac Huff,3-Part Mixed,6,,
A Rhapsody Of Christmas,Ed Lojeski,SAB,19,,
A Very Merry Christmas,Gene Grier and David Lantz,3-Part Mixed,27,,
A Wind Has Blown The Rain Away,Andrew Imbrie,3-Part,1,,
ABC,Roger Emerson,SAB,15,,
Add A Riff,Sol Berkowitz,SATB,1,,
"Addams Family,",Mark Brymer,3-Part Mixed,39,,
Africa,Philip Lawson,SATTBB,17,,
African Noel,Patrick M. Liebergen,SAB,1,,
"Agincort Song, The",J. Stanley Sheppard,TTBB,1,,
Agnus Dei,Patrick M. Liebergen,SAB,1,,
Agnus Dei Canon,Donald Moore,2-Part,21,,
Ain't No Mountain High,Arr. Roger Emerson,SATB,18,,
Aint'a That A Good News,William Dawson,SATB,23,,
All Earth Sing Praise,Ned Rorem,SATB,1,,
All I Want For Christmas,Mac Huff,SAB,21,,
All I Want For Christmas Is You,Mark Brymer,2-Part,13,,
All of Me,Ed Lojeski,SATB,3,,
All Shall Be Well,Elaine Hagenberg,SSAA,1,,
All You Need Is Love,Mac Huff,SATB,1,,
Almost Like Being In Love,Ed Lojeski,3-Part Mixed,17,,
Amazing Grace,John Rutter,SATB,4,,
America Shall Be,Joseph M. Martin,3-Part Mixed,1,,
America the Beautiful,Roger Emerson,SAB,21,,
America!,Kirby Shaw,SATB,16,,
American Anthems,Roger Emerson,SATB,9,,
American Pie,Mac Huff,SATB,3,,
An American Medley,Roger Emerson,SATB,1,,
An English Folk Song Suite,Ed Lojeski,SATB,2,,
Another Day Of Sun,Mark Brymer,SATB,1,,
Anything Goes,Kirby Shaw,SATB,1,,
Appalachian Spring,Ed Lojeski,SATB,5,,
As Long As I Have Music,Brad Printz,3-Part Mixed,1,,
As Long As There's Christmas,Tom Fettke,3-Part,1,,
Autumn Leaves,Kirby Shaw,SAB,1,,
Babylon's Fallin',William Dawson,SATB,1,,
Ballad of the Shape of Things,Ed Lojeski,SATB,1,,
Bananeira,Andre Thomas,2-Part,1,,
Barbershop By George,Ed Lojeski,TTBB,1,,
Battle Hymn of the Republic,Peter J. Wilhousky,SATB,10,,
Beautiful World,Mark Brymer,2-Part,1,,
"Because You Loved Me, Celine Dion",Teena Chinn,SATB,1,,
Beethoven's Wig,Ed Lojeski,SATB,1,,
Beyond The Sea,Roger Emerson,SATB,3,,
Big Bright Beautiful World,Ed Lojeski,2-Part,1,,
Bill Bailey Won't You Please Come Home,Kirby Shaw,SATB,1,,
Bist Du Bei Mir,J.S. Bach,2-Part,1,,
Blue Moon,Dave and Jean Perry,SATB,1,,
Born to Run,Mark Brymer,SATB,1,,
Brahms Lullaby,Robert S. Cohen,SSA,1,,
Brand New Day,Roger Emerson,3-Part Mixed,1,,
Bring Him Home,Mark Brymer,SAB,1,,
Broadway Baby,Bill Holcombe,SAB,1,,
Building Bridges,Roger Emerson,3-Part Mixed,1,,
California Dreamin,Mac Huff,SAB,2,,
California Girls,John Higgins,SAB,1,,
Can't Help Falling In Love With You,Ed Lojeski,SATB,1,,
Can't Stop The Feeling,Mark Brymer,SATB,8,,
Can't Stop The Feeling 3-Part,Mark Brymer,3-Part Mixed,12,,
Cantar!,Jay Althouse,SATB,6,,
Cantate!,John Leavitt,SSA,1,,
Carol of The Bells,Peter J. Wilhousky,SAB,1,,
Cats,Ed Lojeski,SATB,1,,
Celebrate America!,Kirby Shaw,3-Part,21,,
Celebrate Kwanzaa,Lois Brownsey and Marti Lunn Lantz,3-Part,1,,
Celebrate The Future Hand In Hand,Roger Emerson,2-Part,9,,
Celebrate The Season,Patsy Ford Simms,2-Part,20,,
Chantez Alleluia!,Dave and Jean Perry,2-Part,26,,
Chattanooga Choo Choo,Pete Schmutte,SAB,22,,
Cherish,Terry Kirkman,SAB,1,,
Cherry Blossoms,George L. O. Strid & Mary Donnelly,2-Part,18,,
Chicago In Concert,Roger Emerson,SATB,8,,
Chili Con Carne,Andres Edenroth,SSATB,1,,
Ching-A-Ring Chaw,Irving Fine,SSAA,1,,
Christmas In Your Eyes,Carl Strommen,3-Part,17,,
"Christmas Jazz Trio, A",Michele Weir,SATB,6,,
Christmas Memories,Carl Strommen,SATB,9,,
Christmas Once Again!,Don Besig and Nancy Price,2-Part,29,,
Christmas Pops Trio,Jay Althouse,2-Part,6,,
Christmas Remembered,Carl Strommen,3-Part,6,,
Christmas Round,Hank Beebe,2-Part,19,,
Christmas Sleigh,Marshall Cartledge,SATB,26,,
Christmas Time Is Here,Ed Lojeski,2-Part,11,,
Christmas Time!,Jeff Funk,3-Part,10,,
"Christmas Waltz, The",Mac Huff,SAB,17,,
"Christmas Wish, A",Kevin Jensen,SATB,23,,
Christmas Wishes,Kirby Shaw,SAB,11,,
Christmas With Johnny Marks,Anita Kerr,SAB,6,,
Circle,Mac Huff,SAB,15,,
Circle Of Life,Keith Christopher,SATB,3,,
Circus Band,Charles E. Ives,SATB,21,,
City of Stars,Roger Emerson,SATB,23,,
"Civil War, The",Mark Brymer,SATB,1,,
Claim a Dream,Lloyd Larson,SATB,1,,
Clap Your Hands and Sing Hallelujah,Don Besig and Nancy Price,2-Part,1,,
Cloud Song,Bill Whelan,SATB,1,,
Cold Snap,Mark Hayes,2-Part,1,,
Colors Of The Wind,Mac Huff,SAB,22,,
Come In From the Rain,Ed Lojeski,SAB,14,,
Come Joyfully Sing,Patrick M. Liebergen,SAB,1,,
Come Sail Away,Kirby Shaw,SATB,1,,
Come What May,David Lawrence,SATB,1,,
"Come, Ye Sons of Art",Emily Crocker,3-Part,1,,
Consider Yourself,Norman Leyden,SATB,1,,
Cool,Ed Lojeski,SATB,1,,
Crazy Little Thing Called Love,Greg Gilpin,SAB,11,,
Crazy Little Thing Called Love,Kirby Shaw,SATB,1,,
Daydream Believer,Tom Fettke,SAB,1,,
Deep River,Wm. Arms Fisher,SATB,1,,
Diamonds Are A Girl's Best Friend,Mac Huff,SSA,1,,
Do You Hear What I Hear?,Harry Simeone,SAB,25,,
Do You Want To Build A Snowman,Mac Huff,SSA,6,,
Don't Cry For Me Argentina,Audrey Snyder,SAB,1,,
Don't Stop Believin,Mark Brymer,SATB,1,,
Down To The River To Pray,Shawn Kirchner,SATB,3,,
E Tenebris,Eleanor Daley,SATB,1,,
Earth Song,Frank Ticheli,SATB,2,,
Eleanor Rigby,Mac Huff,SATB,1,,
Embraceable You,Donald Feltmate,TTBB,1,,
Endless Night,Mark Brymer,SATB,1,,
Ev'ry Valley,Edwin Fissinger,SSA,1,,
Every Breath You Take,Mac Huff,SAB,14,,
Everything's Alright,Mac Huff,SATB,1,,
Faithfully,Roger Emerson,SATB,10,,
Feliz Navidad,Mark Brymer,3-Part Mixed,10,,
Final Countdown,Mac Huff,SATB,1,,
Finding Nemo Choral Highlights,Audrey Snyder,SATB,1,,
Fly Me To The Moon,Kirby Shaw,SATB,3,,
Footloose,Tom Fettke,3-Part,1,,
For Good,Roger Emerson,SATB,13,,
For The Beauty of The Earth,John Rutter,SATB,4,,
Forever Young,Ed Lojeski,SAB,5,,
Forty-Second Street,Mac Huff,SATB,1,,
From A Distance,Roger Emerson,SAB,17,,
From Here On,Mark Brymer,SATB,1,,
Fun Fun Fun,Mac Huff,SAB,1,,
Gimme! Gimme! Gimme!,Roger Emerson,3-Part Mixed,1,,
Give Me the Simple Life,Ed Lojeski,SATB,1,,
Give Peace a Chance,Roger Emerson,2-Part,1,,
Gloria,Vivaldi arr. Mason,SATB,5,,
Go Down Moses,Donald Moore,SATB,14,,
God Bless the USA,Roger Emerson,SAB,4,,
"Good King Wenceslas (Jazz, The)",Don Besig and Nancy Price,2-Part,1,,
Good Riddance,Mac Huff,SATB,1,,
Gonna Fly Now,Roger Emerson,SATB,1,,
Greatest Love Of All,Mac Huff,SATB,7,,
Hallelujah,Pentatonix,SATB,1,,
Happy,Mark Brymer,SATB,1,,
Happy Days,Pete Schmutte,SAB,24,,
Happy Holidays,Ed Lojeski,3-Part Mixed,1,,
Happy Xmas,Mark Brymer,SAB,1,,
Hello,Mark Brymer,SAB,1,,
Her Voice,Mac Huff,SATB,1,,
Hero,Mac Huff,SATB,1,,
Highlights From Mamma Mia,Roger Emerson,SATB,14,,
Highlights from La La Land,Mark Brymer,SATB,1,,
Highlights From The Greatest Showman,Mac Huff,SATB,1,,
Hollywood Swinging,Roger Emerson,SATB,1,,
"Home (Vocal Selections From The Wiz, A)",Ed Lojeski,SATB,1,,
"Hotel California (For Choir, Medley)",Roger Emerson,SAB,8,,
How Far I'll Go,Mark Brymer,SAB,1,,
How Great Thou Art,Roger Emerson,SATB,3,,
Hungarian Dance No. 5,Brahms,SATB,1,,
Hushabye Mountain,Roger Emerson,SAB,1,,
I Believe In Music,Mac Huff,3-Part,1,,
I Can See Clearly Now,Mac Huff,SAB,1,,
I Could Have Danced All Night,Mark Brymer,SAB,1,,
I Don't Want To Walk Without You,Ed Lojeski,SATB,1,,
I Get A Kick Out Of You,Mark Brymer,SATB,1,,
I Got Rhythm,Mac Huff,SATB,1,,
I Have A Dream,Bob Chilcott,SATB,1,,
I Heard The Bells On Christmas Day,Roger Emerson,2-Part,1,,
I Know That My Redeemer Liveth,Handel,SATB,1,,
I Say A Little Prayer,Mark Brymer,SATB,1,,
I Want To Hold Your Hand,Mac Huff,SATB,1,,
I Will Follow Him,Mac Huff,SSA,14,,
I'll Be Home For Christmas,Philip Lawson,SATB,4,,
I'll Be There,Roger Emerson,SATB,2,,
I'll Stand By You,Mark Brymer,SAB,1,,
I'm Still Standing,Roger Emerson,SATB,1,,
I've Got My Love To Keep Me Warm,Mark Brymer,SATB,1,,
If I Ruled The World,Mark Brymer,SAB,1,,
If My People,Mac Huff,SAB,1,,
Imagine,Mark Brymer,SATB,1,,
"In a New York Minute (Medley)",Roger Emerson,SATB,5,,
In The Still Of The Night,Ed Lojeski,SATB,1,,
In the Bleak Midwinter,Harold Darke,SATB,1,,
Intermezzo From Cavalleria Rusticana,Mascagni arr. Cookson,SATB,1,,
Into The Unknown,Mark Brymer,SSA,8,,
It Don't Mean A Thing,Mark Brymer,SATB,4,,
It's a Grand Night For Singing,Kirby Shaw,SATB,1,,
It's Beginning to Look Like Christmas,Ed Lojeski,SAB,3,,
It's the Most Wonderful Time of the Year,Mac Huff,SAB,19,,
Jingle Bell Rock,Tom Fettke,3-Part,17,,
Jingle Bells!,Dave and Jean Perry,2-Part,7,,
Just A Closer Walk,Kirby Shaw,SAB,10,,
Just Sing,Jay Althouse,3-Part Mixed,21,,
Keep Me In Your Heart,Roger Emerson,SATB,1,,
Kentucky Babe,David Clydesdale,SAB,1,,
Kindness,Sara Bareilles arr. Dave Huff,SAB,14,,
Kyrie For Our Time,Kirby Shaw,3-Part Mixed,3,,
Lineage,Andrea Ramsey,SSA,1,,
Love Takes Time,Jerry Nowak,SATB,1,,
Magic To Do,Bruce W. Fisher,SATB,2,,
Man Kind Should Be My Buisness,Oscar Schrammel,SATB,1,,
Memory,Ed Lojeski,SAB,1,,
My Heart Will Go On,Allan Billingsley,SAB,2,,
My Way,Teena Chin,SATB,1,,
Night Fever,Mac Huff,SATB,1,,
Now Let Every Toung Adore Thee,J.S. Bach,SATB,2,,
One Hand One Heart,William Stickles,3-Part,1,,
"Passing Of The Year, The",Daniel Brinsmead,(S)SAB,19,,
Pourquoy Non,Pierre de la Rue,SATB,1,,
Praise Ye The Lord of Hosts,Alexander Arkhangelsky,SAB,1,,
Prayers From The Ark,Ivor R. Davies,SATB,2,,
Ramblin' Man,Bob Burrows and Gregg Sewell,SATB,1,,
Rio,David Jessie,SATB,1,,
Scat Singing Method,Scott Fredricson,SATB,1,,
Sing,Aurdrey Snydewr,3-Part Mixed,60,,
Sister Act,Mac Huff,SSA,1,,
Slections from Fiddler On The Rood,Norman Leyden,SATB,1,,
Smoke Gets In Your Eyes,Kirby Shaw,SATB,2,,
Soul Man,Mac Huff,SATB,3,,
Soul Man,Jeff Funk,SATB,1,,
Stairway To Heaven,Ken Gargaro,SATB,1,,
Storm,Ed Lojeski,SATB,1,,
That's Christmas To Me,Audrey Snyder,SSA,20,,
The Man In The Mirror,Mark Brymer,SATB,1,,
The Winner Takes It All,Ed Lojeski,SAB,1,,
They're Playing My Song,Anita Kerr,SA,1,,
Those Old Player Pianoroll Rags,Arnold Freed,ANY,1,,
Three American Folk Songs,Katherine Davis,Various,4,,
Tonight,William Stickles,3-Part,1,,
Try To Remember,Harvey Schmidt,SSA,1,,
Unchained Melody,Mark Brymer,SAB,1,,
Velvet Shoes,Randall Thompson,2-Part,1,,
Velvet Shoes,Ruth Elaine Schram,Unison/Two Part,1,,
We Won't Stop Dreaming,Pinkzebra,Two-Part,1,,
When You Believe,Audrey Snyder,SATB,1,,
Wind,Robert S. Cohen,SSAA,1,,
Winter Wonderland,Kirby Shaw,SATB,19,,
Yesterday Songs,Niel Diamond,SATB,1,,"""

VOICING_MAP = {
    '3-part mixed': '3-Part Mixed',
    '3-part': '3-Part',
    '2-part': '2-Part',
    'two-part': '2-Part',
    'unison/two part': 'Unison',
    'satb w piano': 'SATB',
    'satb/3-part': 'SATB',
    'satb/sab': 'SATB',
    'satb/ttbb': 'SATB',
    '(s)sab': 'SAB',
    '2-part/3-part': '3-Part Mixed',
    '3-part any comb': '3-Part Mixed',
    'sabar': 'Other',
    'saa': 'SSA',
    'ssab': 'SSAA',
    'ssatb': 'SSATB',
    '4-part speaking': 'Other',
    'any': 'Other',
    'various': 'Other',
    'vocal, piano, guitar': 'Other',
    '': 'Other'
}
VALID = {'SATB','SSAATTBB','SSAA','SATTBB','SSATB','TTBB','TTBBB','SSA','TTB','SAB','SA','TBB','3-Part Mixed','3-Part','2-Part','Unison','Other'}

def norm_voicing(v):
    if not v: return 'Other'
    lo = v.lower().strip()
    if lo in VOICING_MAP: return VOICING_MAP[lo]
    for x in VALID:
        if x.lower() == lo: return x
    return 'Other'

import csv, io
reader = csv.reader(io.StringIO(CSV_DATA.strip()))
rows = []
for i, row in enumerate(reader):
    if i == 0: continue
    if not row or not row[0].strip(): continue
    rows.append({
        'name': row[0].strip(),
        'composer': row[1].strip() if len(row) > 1 else '',
        'voicing': row[2].strip() if len(row) > 2 else '',
        'copies': row[3].strip() if len(row) > 3 else '',
        'lastPerformed': row[4].strip() if len(row) > 4 else '',
    })

print(f"Parsed {len(rows)} rows from CSV")

# Load existing data
with open('/sessions/laughing-lucid-carson/mnt/Code/sheet-music-catalog/data.json') as f:
    data = json.load(f)

existing_titles = {e['title'].lower().strip() for e in data['work']}
print(f"Existing entries: {len(existing_titles)}")

new_entries = []
skipped = []
t = int(time.time() * 1000)
for i, r in enumerate(rows):
    title_key = r['name'].lower().strip()
    if title_key in existing_titles:
        skipped.append(r['name'])
        continue
    new_entries.append({
        '_type': 'octavo',
        '_id': t + i,
        'title': r['name'],
        'composer': r['composer'],
        'voicing': norm_voicing(r['voicing']),
        'genre': '',
        'copies': r['copies'],
        'lastPerformed': r['lastPerformed'],
        'link': ''
    })

print(f"New entries to add: {len(new_entries)}")
print(f"Skipped (already in catalog): {len(skipped)}")
if skipped: print("Skipped:", skipped)

# Prepend new entries
data['work'] = new_entries + data['work']

with open('/sessions/laughing-lucid-carson/mnt/Code/sheet-music-catalog/data.json', 'w') as f:
    json.dump(data, f, indent=2)

print("Done! Total work entries now:", len(data['work']))
